apiVersion: apps/v1
kind: Deployment
metadata:
  name: primuslearning
  labels:
    app: primuslearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primuslearning
  template:
    metadata:
      labels:
        app: primuslearning
    spec:
      containers:
        - name: primuslearning
          image: 464685491297.dkr.ecr.eu-north-1.amazonaws.com/anydb-poc:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
